version: '3'
services:
  dbserver:
    image: your_id/dbserver
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --quiet --eval 'db.runCommand("ping").ok' localhost:27017/test
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - minitwit-network

  webserver:
    image: your_id/webserver
    depends_on:
      dbserver:
        condition: service_healthy
    ports:
      - "5000:5000" # Depending on the OS using port 5000 might be reserved. Change to "5002:5000" or something similar.
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request;print(urllib.request.urlopen('http://localhost:5000/').read())"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
        - minitwit-network

  clidownload:
    image: appropriate/curl
    depends_on:
      webserver:
        condition: service_healthy
    networks:
      - minitwit-network
    entrypoint: sh -c  "curl http://webserver:5000" # If above applies remember to change this as well.

networks:
  minitwit-network:
    name: "minitwit-network"
    external: True